### ISSUE TITLE
Implement Ext.event.gesture

### ISSUE THREAD

**Issue by geoffreymcgill** [extnet/Ext.NET.Pro#569]
Ext.event.gesture.* [TODO] [HIGH]
    - Ext.event.gesture.Drag
    - Ext.event.gesture.EdgeSwipe
    - Ext.event.gesture.LongPress
    - Ext.event.gesture.Pinch
    - Ext.event.gesture.Rotate
    - Ext.event.gesture.Swipe
    - Ext.event.gesture.Tap

**Comment by DaniilVeriga** [comment]
All the gesture events has been added by @vladsch on the AsbstractComponent level in the revision 6180. It went to the 3.0 final release. Closing the Issue.
