### ISSUE TITLE
TreePanel: expanding a node selects it

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET.Pro#604]
http://forums.ext.net/showthread.php?48151
http://www.sencha.com/forum/showthread.php?289477

**Comment by DaniilVeriga** [comment]
Fixed in v3.1.0 beta.

**Comment by fabriciomurta** [comment]
The initial thread allegedly duplicates another and was updated above.

Original Sencha thread: http://www.sencha.com/forum/showthread.php?289477
New thread: https://www.sencha.com/forum/showthread.php?284220
